version: '3'

services:
  cowrie:
    image: cowrie
    ports:
      - "22:2222"
    volumes:
      - ./logs/cowrie:/cowrie/cowrie-git/var/log/cowrie
    networks:
      default:
        ipv4_address: 172.18.0.2

  glastopf:
    image: glastopf
    ports:
      - "80:80"
    volumes:
      - ./logs/glastopf:/opt/glastopf/db
#      - ./logs/glastopf_files:/opt/glastopf/data/files/
    networks:
      default:
        ipv4_address: 172.18.0.3

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
